- src: geerlingguy.nginx
  version: 2.6.0
- src: geerlingguy.php
  version: 3.6.0
- src: geerlingguy.php-versions
  version: 2.1.3
- src: geerlingguy.composer
  version: 1.7.0
- src: geerlingguy.mysql
  version: 2.9.0
- src: geerlingguy.redis
  version: 1.6.0
- src: geerlingguy.varnish
  version: 2.3.0
- src: geerlingguy.java
  version: 1.8.1
- src: https://github.com/agmtr/ansible-role-elasticsearch.git
  name: agmtr.elasticsearch
  version: origin/master
